import { BigInt } from "@graphprotocol/graph-ts";

export enum TransactionType {
  UPDATED_USER_CREDENTIALS = 1,

  USER_AGREED_TO_PRIVACY_POLICY = 2,

  DAO_POOL_CREATED = 3,
  DAO_POOL_PROPOSAL_CREATED = 4,
  DAO_POOL_PROPOSAL_VOTED = 5,
  DAO_POOL_PROPOSAL_VOTE_CANCELED = 6,
  DAO_POOL_PROPOSAL_EXECUTED = 7,

  DAO_POOL_DELEGATED = 8,
  DAO_POOL_UNDELEGATED = 9,
  DAO_POOL_REQUESTED = 10,
  DAO_POOL_REWARD_CLAIMED = 11,
  DAO_POOL_DEPOSITED = 12,
  DAO_POOL_WITHDRAWN = 13,
  DAO_POOL_MOVED_TO_VALIDATORS = 14,
  DAO_POOL_OFFCHAIN_RESULTS_SAVED = 15,

  DAO_VALIDATORS_VOTED = 16,
  DAO_VALIDATORS_PROPOSAL_CREATED = 17,
  DAO_VALIDATORS_PROPOSAL_EXECUTED = 18,
}

export function getEnumBigInt(operation: TransactionType): BigInt {
  return BigInt.fromI32(operation as i32);
}
