import { BigInt } from "@graphprotocol/graph-ts";

export enum TransactionType {
  UPDATED_USER_CREDENTIALS = 1,

  USER_AGREED_TO_PRIVACY_POLICY = 2,

  DAO_POOL_CREATED = 3,
  DAO_POOL_PROPOSAL_CREATED = 4,
  DAO_POOL_PROPOSAL_VOTED = 5,
  DAO_POOL_PROPOSAL_VOTE_CANCELED = 6,
  DAO_POOL_PROPOSAL_EXECUTED = 7,

  DAO_POOL_DELEGATED = 8,
  DAO_POOL_UNDELEGATED = 9,
  DAO_POOL_DELEGATED_TREASURY = 10,
  DAO_POOL_UNDELEGATED_TREASURY = 11,
  DAO_POOL_REWARD_CLAIMED = 12,
  DAO_POOL_VOTING_REWARD_CLAIMED = 13,
  DAO_POOL_DEPOSITED = 14,
  DAO_POOL_WITHDRAWN = 15,
  DAO_POOL_MOVED_TO_VALIDATORS = 16,
  DAO_POOL_OFFCHAIN_RESULTS_SAVED = 17,

  DAO_VALIDATORS_VOTED = 18,
  DAO_VALIDATORS_PROPOSAL_CREATED = 19,
  DAO_VALIDATORS_PROPOSAL_EXECUTED = 20,
}

export function getEnumBigInt(operation: TransactionType): BigInt {
  return BigInt.fromI32(operation as i32);
}
