export const DAY = 86400;
export const BASIC_POOL_NAME = "BASIC_POOL";
export const INVEST_POOL_NAME = "INVEST_POOL";
export const RISKY_PROPOSAL_NAME = "RISKY_PROPOSAL";
export const INVEST_PROPOSAL_NAME = "INVEST_PROPOSAL";
export const PRICE_FEED_ADDRESS = "0x8c4E49523B4df2a5951ad2720cebf5Cf5A07BA89";
