name: "test-graphs"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.x"
          cache: npm

      - name: Install packages
        run: npm run install-all

      - name: Run tests
        run: npm run compile-all && npm run test-all
